---

apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: rokim_cd
  name: svc-rokim-cd

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rokim-cd-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: rokim_cd
  name: rokim-cd-role-binding
subjects:
  - kind: ServiceAccount
    namespace: rokim_cd
    name: svc-rokim-cd
roleRef:
  kind: ClusterRole
  name: rokim-cd-role
  apiGroup: rbac.authorization.k8s.io


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rokim_cd
  namespace: rokim_cd
  labels:
    app.kubernetes.io/name: rokim-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rokim-cd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rokim-cd
    spec:
      serviceAccountName: svc-rokim-cd
      containers:
        - name: rokim-cd
          image: rokim_cd  # Replace with your Docker image and tag
          imagePullPolicy: Always
          volumeMounts:
            - name: config-volume
              mountPath: /etc/rokim_cd
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: rokim-cd-secret
                  key: github_token
      volumes:
        - name: config-volume
          configMap:
            name: rokim-cd-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: rokim_cd
  name: rokim-cd-config
data:
  config.yaml: |
    ---
    - image_name: hugo_blog
      tag: latest
      username: romainmichau
      k8s_namespace: rokim-apps
      k8s_deployment: hugo-blog-draft
    
    - image_name: hugo_blog
      tag: latest
      username: romainmichau
      k8s_namespace: rokim-apps
      k8s_deployment: hugo-blog-prod
    
    - image_name: connect4_ui
      tag: latest
      username: romainmichau
      k8s_namespace: rokim-apps
      k8s_deployment: connect4-ui

---
apiVersion: v1
kind: Secret
metadata:
  namespace: rokim_cd
  name: rokim-cd-secret
type: Opaque
data:
  github_token: "base64 encoded github token"
